# Generated by Django 6.0.6 on 2026-07-08 13:22

import django.core.validators
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Deluxe , Standard Room', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier. Auto-generated from name if left blank.', max_length=120, unique=True)),
                ('total_rooms', models.PositiveIntegerField(default=1, help_text='Number of physical rooms of this category in the hotel')),
                ('description', models.TextField(blank=True, null=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Default/rack rate per night before meal plan or seasonal adjustments', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_capacity', models.IntegerField(default=3, help_text='Total maximum number of guests', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('max_adults', models.IntegerField(default=2, help_text='Maximum number of adults', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_children', models.IntegerField(default=0, help_text='Maximum number of children', validators=[django.core.validators.MinValueValidator(0)])),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated list of amenities (e.g., WiFi, TV, Air Conditioning)', null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck to temporarily disable bookings for this category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room Category',
                'verbose_name_plural': 'Room Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomCategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='room_categories/')),
                ('is_main', models.BooleanField(default=False, help_text='Designate this image as the main/hero image for the room category')),
                ('alt_text', models.CharField(blank=True, help_text='Descriptive text for accessibility and SEO', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.roomcategory')),
            ],
            options={
                'verbose_name': 'Room Category Image',
                'verbose_name_plural': 'Room Category Images',
                'ordering': ['-is_main', 'uploaded_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('room_category', 'is_main'), name='unique_main_image_per_room_category')],
            },
        ),
    ]
