# Generated by Django 6.0.6 on 2026-07-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategoryimage',
            name='label',
            field=models.CharField(choices=[('hero', 'Full HD hero images with sharpening for web display'), ('main', 'Full HD main content images with sharpening'), ('featured', 'Featured images with Full HD resolution and sharpening'), ('thumbnail', 'Preview thumbnails with subtle blur effect'), ('gallery', 'Gallery images with balanced quality and edge enhancement'), ('room_category', 'Room category icons with emboss effect'), ('about', 'About section images with edge enhancement'), ('reviews', 'Testimonial/profile images with subtle blur'), ('team', 'Team member photos with professional sharpening'), ('why_choose_us', 'Feature images with emboss effect'), ('contact', 'Contact section images with edge enhancement'), ('faq', 'FAQ section images with edge enhancement'), ('newsletter', 'Newsletter promotional images with sharpening'), ('footer', 'Footer logos with compact dimensions'), ('nav', 'Navigation icons with small dimensions'), ('home', 'Home page banners with Full HD resolution and sharpening'), ('team_section', 'Team section images with edge enhancement')], default='room_category', help_text='Image label determines processing based on best practices', max_length=50),
        ),
    ]
