# Generated by Django 6.0.6 on 2026-07-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roomcategoryimage_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategoryimage',
            name='label',
            field=models.CharField(choices=[('hero', 'Full HD hero images with sharpening for web display'), ('main', 'Full HD main content images with sharpening'), ('featured', 'Featured images with Full HD resolution and sharpening'), ('thumbnail', 'Preview thumbnails with subtle blur effect'), ('gallery', 'Gallery images with balanced quality and edge enhancement'), ('room_category', 'Room category icons with emboss effect')], default='room_category', help_text='Image label determines processing based on best practices', max_length=50),
        ),
    ]
